[PI-47978] feat: Interaction 요소에 위계를 추가 (~5/18)
wanteddev/montage-ios pull request #42
Opened 2023-05-17 09:28 UTC by deholic

# 개요
- 🔗 이슈 링크 : https://wantedlab.atlassian.net/browse/PI-47970

### 📌 작업 완료 기한
- 2023/05/18

# 수정사항

## 수정 내용
Interaction 요소에 3단계의 위계를 추가 (.light, .normal, .strong) 하여 부모 요소의 특성에 따라 노출 강도를 늘이거나 줄일 수 있도록 변경하였습니다. 추가로 Button 요소들에 위계를 적용하여 노출하도록 수정하였습니다.

# 확인사항
- [x] 동작 확인

2023-05-17 09:43 UTC, jhseo approved these changes

2023-05-18 00:01 UTC, szzang-kr approved these changes

2023-05-18 11:48 UTC, orioncactus requested changes
확인해보았으나 버튼들에 가중치가 적용되지 않고, normal로 출력되는 것 같습니다 😢

[Figma 파일](https://www.figma.com/file/MK6KmtXBxX7ZkoQXfD9MFH/%EA%B0%9C%EC%84%A0%3A-Component?type=design&node-id=554-11335&t=dRcuWw25mYyJgmQT-4)에서 스크린샷과 디자인 컴포넌트를 비교해 색을 정리해보았습니다.

2023-05-19 05:46 UTC, deholic commented
@orioncactus 실 수치를 찍어봤을 때 가중치가 적용된 수치가 나오고 있고 스샷을 찍어서 스포이드로 찍어 봤는데 정상 값이 나오고 있습니다 😢 
혹시 샘플앱 실행하실 때 montage-ios 레포 브랜치를 이 PR의 브랜치인 `feature/PI-47970-opacity-level`로 바꿔 주셨나요?

![스크린샷 2023-05-19 14 44 29](https://github.com/wanteddev/montage-ios/assets/712513/c375412c-8f50-49a8-aed6-fc475b2aca07)
![스크린샷 2023-05-19 14 45 04](https://github.com/wanteddev/montage-ios/assets/712513/aaa947b4-594e-46df-b16b-64291782abb0)

2023-05-19 06:19 UTC, orioncactus commented
> @orioncactus 실 수치를 찍어봤을 때 가중치가 적용된 수치가 나오고 있고 스샷을 찍어서 스포이드로 찍어 봤는데 정상 값이 나오고 있습니다 😢 혹시 샘플앱 실행하실 때 montage-ios 레포 브랜치를 이 PR의 브랜치인 `feature/PI-47970-opacity-level`로 바꿔 주셨나요?
> 
> ![스크린샷 2023-05-19 14 44 29](https://private-user-images.githubusercontent.com/712513/239448089-c375412c-8f50-49a8-aed6-fc475b2aca07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg0NDc3MzExLCJuYmYiOjE2ODQ0NzcwMTEsInBhdGgiOiIvNzEyNTEzLzIzOTQ0ODA4OS1jMzc1NDEyYy04ZjUwLTQ5YTgtYWVkNi1mYzQ3NWIyYWNhMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA1MTlUMDYxNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE4NmIwYjhkNDBjMzdmYjU2NmQzYzE5MTRmNWZkZTM4M2I4MjdiZTc0ZmQ2M2M5NWEwY2FiZmVkOGNkNjM2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3r3dKGmHkSzJclKyXlaVBU5orOpZM8x-pXbBLmUdqbQ) ![스크린샷 2023-05-19 14 45 04](https://private-user-images.githubusercontent.com/712513/239448106-aaa947b4-594e-46df-b16b-64291782abb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJrZXkxIiwiZXhwIjoxNjg0NDc3MzExLCJuYmYiOjE2ODQ0NzcwMTEsInBhdGgiOiIvNzEyNTEzLzIzOTQ0ODEwNi1hYWE5NDdiNC01OTRlLTQ2ZGYtYjE2Yi02NDI5MTc4MmFiYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA1MTlUMDYxNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTYwYjhjOTNlZWMxMDcwNGY0NDM0NTQzZTllZTJjMWY5MDJiOGM5MTNjMmZmZWUwMTJmNTg4ZDUzZTA3ZWJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WQFQJfhy5qkM2c1raAMa0iahZOXzQ8UQcIFN4cow_E4)

아이고 죄송합니다 🙇 오퍼시티 네임만 보고 `feature/PI-47978-change-opacity-names`로 들어갔네요 😂 바로 확인해보겠습니다!

2023-05-19 06:48 UTC, orioncactus approved these changes
혼란을 드려 죄송합니다! 🙇 잘 동작합니다 🤩

2023-05-23 05:16 UTC, merged